### ISSUE TITLE
Supporting json files 

### ISSUE THREAD

**Issue by e-li-23** [flamewei123/DEPN#2]
您好，是否可以共享支持文件，例如与 --priv_data_path 对应的 json 文件等，或者显示此处结构应该是什么的示例文件？

非常感谢！

Hi, would it be possible to share supporting files such as the json files corresponding to --priv_data_path , etc, or example files which show what the structure here should be?

Thanks so much!

**Comment by flamewei123** [comment]
We are glad to tell you that our repository for "DEPN" has been updated. We have added instructions for processing original data and fine-tuning the baseline model, and added the README for running codes. Hope our work can help you.
