### ISSUE TITLE
training stuck on tokenization

### ISSUE THREAD

**Issue by JXL884** [flamewei123/DEPN#3]
Hi there, as I'm running "Finetune BERT on Enron" scripts you recently added. I noticed my training kept stucking on tokenization part where it says: "Running tokenizer on every text in dataset:   0%|                                                                                                                              | 0/1 [00:00<?, ? examples/sW" 

I'm feeding processed train.txt and valid.txt into the model, I'm wondering if you came across similar issues? Or if you made any adjustment based in the default training scripts?

**Comment by flamewei123** [comment]
Sorry I haven't encountered this problem.

Maybe you can try to clone https://github.com/huggingface/transformers.git, and run run_mlm_no_trainer.py under transformers/tree/main/examples/pytorch/language-modeling.

And here are the versions:
```
torch==2.1.1+cu118
transformers==4.21.3
datasets==2.7.1
```

**Comment by JXL884** [comment]
Hi I think the problem solved when you update preprocessing code thanks
