### ISSUE TITLE
Issue when getting memorized tel number

### ISSUE THREAD

**Issue by JXL884** [flamewei123/DEPN#4]
Hi there, as I'm running the get_memerization.py. The code works fine with NAME and RANDOM TEXT. However, for TEL there's a error saying missing a file FileNotFoundError: [Errno 2] No such file or directory: './all_Tel.txt' in line 132. I'm wondering is this something you manually selected, if so could you update this file in the repo. 

Thank you so much

**Comment by flamewei123** [comment]
I`m sorry that the temporarily modification during debugging was not deleted. Please change line 120 in 'preprocess_enron.py' to "save_tels('./all_Tel.txt',Tel_list)", that is, remove the "#" and you will get './all_Tel.txt'.

Thank you for your reminder.
